-- =========================================================================
-- JPA 개발 모드 보완 스크립트 (2) : 앱을 한 번 띄운 "후"에 실행
-- =========================================================================
-- Hibernate 가 엔티티로 테이블을 만든 뒤에 실행해야 한다.
-- (부분 인덱스와 뷰가 Hibernate 가 만든 테이블에 의존한다)
--
--   psql "$DB_URL" -f src/main/resources/db/migration/manual/jpa-02-after-boot.sql
--
-- 이 파일은 Flyway 마이그레이션이 아니다. V/R 접두사를 붙이지 말 것.
-- 전부 IF NOT EXISTS / OR REPLACE 라 여러 번 실행해도 안전하다.
--
-- 내용은 V1~V15 마이그레이션에서 "Hibernate 가 만들 수 없는 것"만 추출한 것이고,
-- 각 구문 위의 `-- from V*.sql` 주석이 원본 위치다.
-- 스키마를 바꾸면 마이그레이션과 이 파일 양쪽을 함께 고쳐야 한다.
--
-- 일부러 제외한 것:
--   * CHECK 제약 66개 - 데이터 검증용이라 개발 루프 동작에는 영향 없음
--   * 엔티티 테이블의 일반 인덱스 - 로컬 데이터량에서는 성능 차이 없음
-- =========================================================================

-- ==========================================================================
-- 1. 엔티티가 없는 공공데이터 테이블 8개
-- JPA 엔티티가 아예 없어서 Hibernate 가 만들지 않는다. 없으면 수집 서비스가 전부 실패한다.
-- ==========================================================================

-- from V4__create_commercial_estimated_sales.sql
CREATE TABLE IF NOT EXISTS commercial_estimated_sales (
    commercial_estimated_sales_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stdr_yyqu_cd VARCHAR(5) NOT NULL,
    trdar_se_cd VARCHAR(20),
    trdar_se_cd_nm VARCHAR(100),
    trdar_cd VARCHAR(30) NOT NULL,
    trdar_cd_nm VARCHAR(150),
    svc_induty_cd VARCHAR(30) NOT NULL,
    svc_induty_cd_nm VARCHAR(100),

    thsmon_selng_amt BIGINT NOT NULL DEFAULT 0,
    thsmon_selng_co BIGINT NOT NULL DEFAULT 0,

    mdwk_selng_amt BIGINT NOT NULL DEFAULT 0,
    wkend_selng_amt BIGINT NOT NULL DEFAULT 0,
    mon_selng_amt BIGINT NOT NULL DEFAULT 0,
    tues_selng_amt BIGINT NOT NULL DEFAULT 0,
    wed_selng_amt BIGINT NOT NULL DEFAULT 0,
    thur_selng_amt BIGINT NOT NULL DEFAULT 0,
    fri_selng_amt BIGINT NOT NULL DEFAULT 0,
    sat_selng_amt BIGINT NOT NULL DEFAULT 0,
    sun_selng_amt BIGINT NOT NULL DEFAULT 0,

    tmzon_00_06_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_06_11_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_11_14_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_14_17_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_17_21_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_21_24_selng_amt BIGINT NOT NULL DEFAULT 0,

    ml_selng_amt BIGINT NOT NULL DEFAULT 0,
    fml_selng_amt BIGINT NOT NULL DEFAULT 0,

    agrde_10_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_20_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_30_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_40_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_50_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_60_above_selng_amt BIGINT NOT NULL DEFAULT 0,

    mdwk_selng_co BIGINT NOT NULL DEFAULT 0,
    wkend_selng_co BIGINT NOT NULL DEFAULT 0,
    mon_selng_co BIGINT NOT NULL DEFAULT 0,
    tues_selng_co BIGINT NOT NULL DEFAULT 0,
    wed_selng_co BIGINT NOT NULL DEFAULT 0,
    thur_selng_co BIGINT NOT NULL DEFAULT 0,
    fri_selng_co BIGINT NOT NULL DEFAULT 0,
    sat_selng_co BIGINT NOT NULL DEFAULT 0,
    sun_selng_co BIGINT NOT NULL DEFAULT 0,

    tmzon_00_06_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_06_11_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_11_14_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_14_17_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_17_21_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_21_24_selng_co BIGINT NOT NULL DEFAULT 0,

    ml_selng_co BIGINT NOT NULL DEFAULT 0,
    fml_selng_co BIGINT NOT NULL DEFAULT 0,

    agrde_10_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_20_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_30_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_40_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_50_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_60_above_selng_co BIGINT NOT NULL DEFAULT 0,

    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_commercial_estimated_sales_quarter_area_industry
        UNIQUE (stdr_yyqu_cd, trdar_cd, svc_induty_cd),

    CONSTRAINT chk_commercial_estimated_sales_amounts CHECK (
        thsmon_selng_amt >= 0
        AND thsmon_selng_co >= 0
        AND mdwk_selng_amt >= 0
        AND wkend_selng_amt >= 0
        AND mon_selng_amt >= 0
        AND tues_selng_amt >= 0
        AND wed_selng_amt >= 0
        AND thur_selng_amt >= 0
        AND fri_selng_amt >= 0
        AND sat_selng_amt >= 0
        AND sun_selng_amt >= 0
        AND mdwk_selng_co >= 0
        AND wkend_selng_co >= 0
        AND mon_selng_co >= 0
        AND tues_selng_co >= 0
        AND wed_selng_co >= 0
        AND thur_selng_co >= 0
        AND fri_selng_co >= 0
        AND sat_selng_co >= 0
        AND sun_selng_co >= 0
    )
);

-- from V4__create_commercial_estimated_sales.sql
CREATE INDEX IF NOT EXISTS idx_commercial_estimated_sales_stdr_yyqu_cd
    ON commercial_estimated_sales(stdr_yyqu_cd);

-- from V4__create_commercial_estimated_sales.sql
CREATE INDEX IF NOT EXISTS idx_commercial_estimated_sales_trdar_cd
    ON commercial_estimated_sales(trdar_cd);

-- from V4__create_commercial_estimated_sales.sql
CREATE INDEX IF NOT EXISTS idx_commercial_estimated_sales_svc_induty_cd
    ON commercial_estimated_sales(svc_induty_cd);

-- from V5__create_small_business_stores.sql
-- 공공데이터 원문을 보존하고 내부 stores 도메인과는 별도로 관리한다.
CREATE TABLE IF NOT EXISTS small_business_stores (
    small_business_store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id VARCHAR(30) NOT NULL,
    commercial_area_code VARCHAR(30) NOT NULL,
    store_name VARCHAR(200) NOT NULL,
    branch_name VARCHAR(200),
    large_industry_code VARCHAR(10),
    large_industry_name VARCHAR(100),
    medium_industry_code VARCHAR(10),
    medium_industry_name VARCHAR(100),
    small_industry_code VARCHAR(10),
    small_industry_name VARCHAR(100),
    standard_industry_code VARCHAR(20),
    standard_industry_name VARCHAR(150),
    sido_code VARCHAR(10),
    sido_name VARCHAR(50),
    sigungu_code VARCHAR(10),
    sigungu_name VARCHAR(50),
    administrative_dong_code VARCHAR(20),
    administrative_dong_name VARCHAR(50),
    legal_dong_code VARCHAR(20),
    legal_dong_name VARCHAR(50),
    lot_number_address VARCHAR(500),
    road_name_address VARCHAR(500),
    building_management_number VARCHAR(30),
    building_name VARCHAR(200),
    floor_number VARCHAR(30),
    room_number VARCHAR(30),
    longitude DECIMAL(12, 8),
    latitude DECIMAL(12, 8),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_small_business_stores_store_id UNIQUE (store_id)
);

-- from V5__create_small_business_stores.sql
CREATE INDEX IF NOT EXISTS idx_small_business_stores_commercial_area_code
    ON small_business_stores(commercial_area_code);

-- from V5__create_small_business_stores.sql
CREATE INDEX IF NOT EXISTS idx_small_business_stores_industry
    ON small_business_stores(large_industry_code, medium_industry_code, small_industry_code);

-- from V5__create_small_business_stores.sql
CREATE INDEX IF NOT EXISTS idx_small_business_stores_administrative_dong
    ON small_business_stores(administrative_dong_code);

-- from V5__create_small_business_stores.sql
CREATE INDEX IF NOT EXISTS idx_small_business_stores_legal_dong
    ON small_business_stores(legal_dong_code);

-- from V7__allow_null_small_business_store_name.sql
ALTER TABLE small_business_stores
    ALTER COLUMN store_name DROP NOT NULL;

-- from V8__create_reb_small_retail_rents.sql
CREATE TABLE IF NOT EXISTS reb_small_retail_rent_areas (
    reb_small_retail_rent_area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_area_key VARCHAR(64) NOT NULL,
    source_row_number INTEGER NOT NULL,
    area_name VARCHAR(100) NOT NULL,
    area_path VARCHAR(500) NOT NULL,
    area_level SMALLINT NOT NULL,
    region_id BIGINT REFERENCES regions(region_id),
    commercial_area_id BIGINT REFERENCES commercial_areas(commercial_area_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_reb_small_retail_rent_areas_source_key UNIQUE (source_area_key),
    CONSTRAINT ck_reb_small_retail_rent_areas_single_mapping CHECK (
        region_id IS NULL OR commercial_area_id IS NULL
    )
);

-- from V8__create_reb_small_retail_rents.sql
CREATE TABLE IF NOT EXISTS reb_small_retail_rent_metrics (
    reb_small_retail_rent_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reb_small_retail_rent_area_id BIGINT NOT NULL
        REFERENCES reb_small_retail_rent_areas(reb_small_retail_rent_area_id),
    reference_year SMALLINT NOT NULL,
    reference_quarter SMALLINT NOT NULL,
    rent_per_square_meter_thousand_krw DECIMAL(12, 3) NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    source_file_hash VARCHAR(64) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT ck_reb_small_retail_rent_metrics_quarter CHECK (reference_quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_reb_small_retail_rent_metrics_rent CHECK (
        rent_per_square_meter_thousand_krw >= 0
    ),
    CONSTRAINT uq_reb_small_retail_rent_metrics_area_period UNIQUE (
        reb_small_retail_rent_area_id, reference_year, reference_quarter
    )
);

-- from V8__create_reb_small_retail_rents.sql
CREATE INDEX IF NOT EXISTS idx_reb_small_retail_rent_areas_region
    ON reb_small_retail_rent_areas(region_id);

-- from V8__create_reb_small_retail_rents.sql
CREATE INDEX IF NOT EXISTS idx_reb_small_retail_rent_areas_commercial_area
    ON reb_small_retail_rent_areas(commercial_area_id);

-- from V8__create_reb_small_retail_rents.sql
CREATE INDEX IF NOT EXISTS idx_reb_small_retail_rent_metrics_period
    ON reb_small_retail_rent_metrics(reference_year, reference_quarter);

-- from V10__create_kosis_business_survival_rates.sql
CREATE TABLE IF NOT EXISTS kosis_business_survival_rates (
    kosis_business_survival_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id VARCHAR(20) NOT NULL,
    table_id VARCHAR(50) NOT NULL,
    table_name VARCHAR(200),
    industry_code VARCHAR(50) NOT NULL,
    industry_name VARCHAR(200) NOT NULL,
    classification_name VARCHAR(200),
    item_id VARCHAR(50) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    unit_name VARCHAR(30) NOT NULL,
    period_type VARCHAR(10) NOT NULL,
    reference_year INT NOT NULL,
    survival_rate DECIMAL(7,3) NOT NULL,
    source_updated_at VARCHAR(30),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_kosis_business_survival_rate
        UNIQUE (table_id, industry_code, item_id, reference_year),
    CONSTRAINT chk_kosis_business_survival_reference_year
        CHECK (reference_year BETWEEN 1900 AND 2200),
    CONSTRAINT chk_kosis_business_survival_rate
        CHECK (survival_rate BETWEEN 0 AND 100)
);

-- from V10__create_kosis_business_survival_rates.sql
CREATE INDEX IF NOT EXISTS idx_kosis_business_survival_year_industry
    ON kosis_business_survival_rates(reference_year, industry_code);

-- from V11__create_kosis_business_counts.sql
CREATE TABLE IF NOT EXISTS kosis_business_counts (
    kosis_business_count_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id VARCHAR(20) NOT NULL,
    table_id VARCHAR(50) NOT NULL,
    table_name VARCHAR(200),
    industry_code VARCHAR(50) NOT NULL,
    industry_name VARCHAR(200) NOT NULL,
    classification_name VARCHAR(200),
    item_id VARCHAR(50) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    unit_name VARCHAR(30) NOT NULL,
    period_type VARCHAR(10) NOT NULL,
    reference_year INT NOT NULL,
    business_count DECIMAL(20, 3) NOT NULL,
    source_updated_at VARCHAR(30),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_kosis_business_count
        UNIQUE (table_id, industry_code, item_id, reference_year),
    CONSTRAINT chk_kosis_business_count_reference_year
        CHECK (reference_year BETWEEN 1900 AND 2200),
    CONSTRAINT chk_kosis_business_count_non_negative
        CHECK (business_count >= 0)
);

-- from V11__create_kosis_business_counts.sql
CREATE INDEX IF NOT EXISTS idx_kosis_business_count_year_industry
    ON kosis_business_counts(reference_year, industry_code);

-- from V13__create_seoul_sdot_foot_traffic.sql
CREATE TABLE IF NOT EXISTS seoul_sdot_foot_traffic (
    seoul_sdot_foot_traffic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(50),
    serial_number VARCHAR(100) NOT NULL,
    sensing_time TIMESTAMP NOT NULL,
    region_type VARCHAR(100),
    autonomous_district VARCHAR(100),
    administrative_district VARCHAR(100),
    visitor_count BIGINT NOT NULL,
    registered_at TIMESTAMP,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_seoul_sdot_foot_traffic_sensor_time
        UNIQUE (serial_number, sensing_time),
    CONSTRAINT chk_seoul_sdot_foot_traffic_visitor_count
        CHECK (visitor_count >= 0)
);

-- from V13__create_seoul_sdot_foot_traffic.sql
CREATE INDEX IF NOT EXISTS idx_seoul_sdot_foot_traffic_sensing_time
    ON seoul_sdot_foot_traffic(sensing_time);

-- from V13__create_seoul_sdot_foot_traffic.sql
CREATE INDEX IF NOT EXISTS idx_seoul_sdot_foot_traffic_district
    ON seoul_sdot_foot_traffic(autonomous_district, administrative_district);

-- from V15__create_seoul_realtime_city_populations.sql
CREATE TABLE IF NOT EXISTS seoul_realtime_city_populations (
    seoul_realtime_city_population_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code VARCHAR(30) NOT NULL,
    area_name VARCHAR(150) NOT NULL,
    congestion_level VARCHAR(30),
    congestion_message VARCHAR(1000),
    population_min BIGINT NOT NULL,
    population_max BIGINT NOT NULL,
    estimated_population BIGINT NOT NULL,
    male_population_rate DECIMAL(6, 3),
    female_population_rate DECIMAL(6, 3),
    population_rate_0 DECIMAL(6, 3),
    population_rate_10 DECIMAL(6, 3),
    population_rate_20 DECIMAL(6, 3),
    population_rate_30 DECIMAL(6, 3),
    population_rate_40 DECIMAL(6, 3),
    population_rate_50 DECIMAL(6, 3),
    population_rate_60 DECIMAL(6, 3),
    population_rate_70 DECIMAL(6, 3),
    resident_population_rate DECIMAL(6, 3),
    non_resident_population_rate DECIMAL(6, 3),
    replacement_used BOOLEAN NOT NULL DEFAULT false,
    population_time TIMESTAMP NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_seoul_realtime_city_population_area_time
        UNIQUE (area_code, population_time),
    CONSTRAINT chk_seoul_realtime_city_population_range
        CHECK (population_min >= 0 AND population_max >= population_min),
    CONSTRAINT chk_seoul_realtime_city_population_estimate
        CHECK (estimated_population BETWEEN population_min AND population_max)
);

-- from V15__create_seoul_realtime_city_populations.sql
CREATE INDEX IF NOT EXISTS idx_seoul_realtime_city_population_area_latest
    ON seoul_realtime_city_populations(area_code, population_time DESC);

-- ==========================================================================
-- 2. 엔티티 테이블 보정
-- UNLOGGED 전환(WAL 증가 방지)과 엔티티 @Column(length=50) 보다 넓은 실제 컬럼 정의.
-- ==========================================================================

-- from V3__set_unlogged_volatile_tables.sql
-- WAL 아카이브 / EBS 비정상 증가 방지를 위해 휘발성이고 유실돼도 재생성 가능한 테이블을 UNLOGGED로 전환한다.

ALTER TABLE refresh_tokens SET UNLOGGED;

-- from V9__expand_commercial_data_collect_target_key.sql
ALTER TABLE commercial_data_collect_histories
    ALTER COLUMN target_key TYPE VARCHAR(100);

-- ==========================================================================
-- 3. 부분 인덱스 16개
-- WHERE 절이 붙은 인덱스는 JPA 로 표현할 수 없다. 중복 수집/중복 스냅샷을 막는 정합성 장치.
-- ==========================================================================

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_regions_code ON regions (code) WHERE code IS NOT NULL;

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_stores_code ON stores (code) WHERE code IS NOT NULL;

-- from V1__init_seed_core_schema.sql
CREATE INDEX IF NOT EXISTS idx_builder_stores_public_uploaded ON builder_stores(uploaded_at DESC) WHERE visibility_status = 'PUBLIC';

-- from V1__init_seed_core_schema.sql
CREATE INDEX IF NOT EXISTS idx_builder_stores_public_likes ON builder_stores(like_count DESC) WHERE visibility_status = 'PUBLIC';

-- from V1__init_seed_core_schema.sql
CREATE INDEX IF NOT EXISTS idx_builder_stores_public_sales ON builder_stores(expected_monthly_sales DESC) WHERE visibility_status = 'PUBLIC';

-- from V1__init_seed_core_schema.sql
CREATE INDEX IF NOT EXISTS idx_builder_stores_public_profit ON builder_stores(expected_profit_rate DESC) WHERE visibility_status = 'PUBLIC';

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_floating_population_region
ON floating_population_metrics (region_id, reference_date, time_slot_start, age_group, gender)
WHERE region_id IS NOT NULL;

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_floating_population_commercial_area
ON floating_population_metrics (commercial_area_id, reference_date, time_slot_start, age_group, gender)
WHERE commercial_area_id IS NOT NULL;

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_rent_market_region_month
ON rent_market_monthly_metrics (region_id, reference_month)
WHERE region_id IS NOT NULL;

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_rent_market_commercial_area_month
ON rent_market_monthly_metrics (commercial_area_id, reference_month)
WHERE commercial_area_id IS NOT NULL;

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_score_store_month
ON score_snapshots (store_id, score_type, reference_month)
WHERE target_type = 'STORE';

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_score_builder_store_month
ON score_snapshots (builder_store_id, score_type, reference_month)
WHERE target_type = 'BUILDER_STORE';

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_score_commercial_area_month
ON score_snapshots (commercial_area_id, score_type, reference_month)
WHERE target_type = 'COMMERCIAL_AREA';

-- from V1__init_seed_core_schema.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_score_region_month
ON score_snapshots (region_id, score_type, reference_month)
WHERE target_type = 'REGION';

-- from V4__create_commercial_estimated_sales.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_commercial_data_collect_histories_completed
    ON commercial_data_collect_histories(data_type, target_key)
    WHERE status = 'COMPLETED';

-- from V6__prevent_concurrent_commercial_data_collection.sql
CREATE UNIQUE INDEX IF NOT EXISTS uq_commercial_data_collect_histories_running
    ON commercial_data_collect_histories(data_type, target_key)
    WHERE status = 'RUNNING';

-- ==========================================================================
-- 4. 뷰 4개
-- Hibernate 는 뷰를 만들지 못한다. JdbcPublicDataResolver 가 조회하므로 없으면 런타임에 실패한다.
-- ==========================================================================

-- from V12__create_kosis_business_rates_view.sql
CREATE OR REPLACE VIEW kosis_business_rates AS
SELECT
    organization_id,
    table_id,
    industry_code,
    MAX(industry_name) AS industry_name,
    reference_year,
    MAX(business_count) FILTER (WHERE item_id = 'T01') AS active_business_count,
    MAX(business_count) FILTER (WHERE item_id = 'T02') AS new_business_count,
    MAX(business_count) FILTER (WHERE item_id = 'T03') AS closed_business_count,
    ROUND(
        MAX(business_count) FILTER (WHERE item_id = 'T02')
            / NULLIF(MAX(business_count) FILTER (WHERE item_id = 'T01'), 0)
            * 100,
        3
    ) AS new_business_rate,
    ROUND(
        MAX(business_count) FILTER (WHERE item_id = 'T03')
            / NULLIF(MAX(business_count) FILTER (WHERE item_id = 'T01'), 0)
            * 100,
        3
    ) AS closure_rate
FROM kosis_business_counts
WHERE item_id IN ('T01', 'T02', 'T03')
GROUP BY organization_id, table_id, industry_code, reference_year;

-- from V14__create_seoul_sdot_traffic_metric_views.sql
CREATE OR REPLACE VIEW seoul_sdot_latest_sensor_traffic AS
SELECT DISTINCT ON (serial_number)
    serial_number,
    model_name,
    sensing_time,
    region_type,
    autonomous_district,
    administrative_district,
    visitor_count,
    registered_at
FROM seoul_sdot_foot_traffic
ORDER BY serial_number, sensing_time DESC;

-- from V14__create_seoul_sdot_traffic_metric_views.sql
CREATE OR REPLACE VIEW seoul_sdot_district_traffic_metrics AS
SELECT
    autonomous_district,
    administrative_district,
    COUNT(*) AS sensor_count,
    SUM(visitor_count) AS total_visitor_count,
    ROUND(AVG(visitor_count), 3) AS average_visitor_count,
    MIN(sensing_time) AS oldest_sensing_time,
    MAX(sensing_time) AS latest_sensing_time
FROM seoul_sdot_latest_sensor_traffic
WHERE autonomous_district IS NOT NULL
  AND autonomous_district <> ''
  AND administrative_district IS NOT NULL
  AND administrative_district <> ''
GROUP BY autonomous_district, administrative_district;

-- from V15__create_seoul_realtime_city_populations.sql
CREATE OR REPLACE VIEW seoul_realtime_city_latest_populations AS
SELECT DISTINCT ON (area_code)
    area_code,
    area_name,
    congestion_level,
    population_min,
    population_max,
    estimated_population,
    male_population_rate,
    female_population_rate,
    population_rate_0,
    population_rate_10,
    population_rate_20,
    population_rate_30,
    population_rate_40,
    population_rate_50,
    population_rate_60,
    population_rate_70,
    resident_population_rate,
    non_resident_population_rate,
    replacement_used,
    population_time
FROM seoul_realtime_city_populations
ORDER BY area_code, population_time DESC;
