CREATE TABLE kosis_business_counts (
    kosis_business_count_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id VARCHAR(20) NOT NULL,
    table_id VARCHAR(50) NOT NULL,
    table_name VARCHAR(200),
    industry_code VARCHAR(50) NOT NULL,
    industry_name VARCHAR(200) NOT NULL,
    classification_name VARCHAR(200),
    item_id VARCHAR(50) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    unit_name VARCHAR(30) NOT NULL,
    period_type VARCHAR(10) NOT NULL,
    reference_year INT NOT NULL,
    business_count DECIMAL(20, 3) NOT NULL,
    source_updated_at VARCHAR(30),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_kosis_business_count
        UNIQUE (table_id, industry_code, item_id, reference_year),
    CONSTRAINT chk_kosis_business_count_reference_year
        CHECK (reference_year BETWEEN 1900 AND 2200),
    CONSTRAINT chk_kosis_business_count_non_negative
        CHECK (business_count >= 0)
);

CREATE INDEX idx_kosis_business_count_year_industry
    ON kosis_business_counts(reference_year, industry_code);
