CREATE TABLE seoul_sdot_foot_traffic (
    seoul_sdot_foot_traffic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(50),
    serial_number VARCHAR(100) NOT NULL,
    sensing_time TIMESTAMP NOT NULL,
    region_type VARCHAR(100),
    autonomous_district VARCHAR(100),
    administrative_district VARCHAR(100),
    visitor_count BIGINT NOT NULL,
    registered_at TIMESTAMP,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_seoul_sdot_foot_traffic_sensor_time
        UNIQUE (serial_number, sensing_time),
    CONSTRAINT chk_seoul_sdot_foot_traffic_visitor_count
        CHECK (visitor_count >= 0)
);

CREATE INDEX idx_seoul_sdot_foot_traffic_sensing_time
    ON seoul_sdot_foot_traffic(sensing_time);

CREATE INDEX idx_seoul_sdot_foot_traffic_district
    ON seoul_sdot_foot_traffic(autonomous_district, administrative_district);
