CREATE TABLE seoul_realtime_city_populations (
    seoul_realtime_city_population_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code VARCHAR(30) NOT NULL,
    area_name VARCHAR(150) NOT NULL,
    congestion_level VARCHAR(30),
    congestion_message VARCHAR(1000),
    population_min BIGINT NOT NULL,
    population_max BIGINT NOT NULL,
    estimated_population BIGINT NOT NULL,
    male_population_rate DECIMAL(6, 3),
    female_population_rate DECIMAL(6, 3),
    population_rate_0 DECIMAL(6, 3),
    population_rate_10 DECIMAL(6, 3),
    population_rate_20 DECIMAL(6, 3),
    population_rate_30 DECIMAL(6, 3),
    population_rate_40 DECIMAL(6, 3),
    population_rate_50 DECIMAL(6, 3),
    population_rate_60 DECIMAL(6, 3),
    population_rate_70 DECIMAL(6, 3),
    resident_population_rate DECIMAL(6, 3),
    non_resident_population_rate DECIMAL(6, 3),
    replacement_used BOOLEAN NOT NULL DEFAULT false,
    population_time TIMESTAMP NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_seoul_realtime_city_population_area_time
        UNIQUE (area_code, population_time),
    CONSTRAINT chk_seoul_realtime_city_population_range
        CHECK (population_min >= 0 AND population_max >= population_min),
    CONSTRAINT chk_seoul_realtime_city_population_estimate
        CHECK (estimated_population BETWEEN population_min AND population_max)
);

CREATE INDEX idx_seoul_realtime_city_population_area_latest
    ON seoul_realtime_city_populations(area_code, population_time DESC);

CREATE VIEW seoul_realtime_city_latest_populations AS
SELECT DISTINCT ON (area_code)
    area_code,
    area_name,
    congestion_level,
    population_min,
    population_max,
    estimated_population,
    male_population_rate,
    female_population_rate,
    population_rate_0,
    population_rate_10,
    population_rate_20,
    population_rate_30,
    population_rate_40,
    population_rate_50,
    population_rate_60,
    population_rate_70,
    resident_population_rate,
    non_resident_population_rate,
    replacement_used,
    population_time
FROM seoul_realtime_city_populations
ORDER BY area_code, population_time DESC;
