CREATE TABLE analysis_collection_runs (
    analysis_collection_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    analysis_type VARCHAR(20) NOT NULL,
    region_code VARCHAR(30) NOT NULL,
    industry_code VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_analysis_collection_run_type
        CHECK (analysis_type IN ('PROFIT', 'SURVIVAL')),
    CONSTRAINT chk_analysis_collection_run_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE analysis_collection_tasks (
    analysis_collection_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_collection_run_id BIGINT NOT NULL
        REFERENCES analysis_collection_runs(analysis_collection_run_id) ON DELETE CASCADE,
    data_type VARCHAR(100) NOT NULL,
    target_key VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(2000),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_analysis_collection_task
        UNIQUE (analysis_collection_run_id, data_type, target_key),
    CONSTRAINT chk_analysis_collection_task_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_analysis_collection_task_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_analysis_collection_runs_user_created
    ON analysis_collection_runs(user_id, created_at DESC);

CREATE INDEX idx_analysis_collection_tasks_run_status
    ON analysis_collection_tasks(analysis_collection_run_id, status);
