CREATE TABLE commercial_area_external_code_mappings (
    commercial_area_external_code_mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercial_area_id BIGINT NOT NULL REFERENCES commercial_areas(commercial_area_id),
    source VARCHAR(50) NOT NULL,
    external_code VARCHAR(100) NOT NULL,
    external_name VARCHAR(200),
    CONSTRAINT uq_commercial_area_external_code_mapping
        UNIQUE (commercial_area_id, source, external_code),
    CONSTRAINT chk_commercial_area_external_code_mapping_source CHECK (
        source IN (
            'SEOUL_ESTIMATED_SALES',
            'SMALL_BUSINESS_STORE',
            'KOSIS_BUSINESS_SURVIVAL_RATE',
            'KOSIS_BUSINESS_COUNT',
            'SEOUL_SDOT_FOOT_TRAFFIC'
        )
    )
);

CREATE TABLE industry_external_code_mappings (
    industry_external_code_mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_id BIGINT NOT NULL REFERENCES industries(industry_id),
    source VARCHAR(50) NOT NULL,
    external_code VARCHAR(100) NOT NULL,
    external_name VARCHAR(200),
    CONSTRAINT uq_industry_external_code_mapping
        UNIQUE (industry_id, source, external_code),
    CONSTRAINT chk_industry_external_code_mapping_source CHECK (
        source IN (
            'SEOUL_ESTIMATED_SALES',
            'SMALL_BUSINESS_STORE',
            'KOSIS_BUSINESS_SURVIVAL_RATE',
            'KOSIS_BUSINESS_COUNT',
            'SEOUL_SDOT_FOOT_TRAFFIC'
        )
    )
);

CREATE INDEX idx_commercial_area_external_code_mappings_lookup
    ON commercial_area_external_code_mappings(commercial_area_id, source);

CREATE INDEX idx_industry_external_code_mappings_lookup
    ON industry_external_code_mappings(industry_id, source);
