CREATE TABLE region_external_code_mappings (
    region_external_code_mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code VARCHAR(30) NOT NULL,
    source VARCHAR(50) NOT NULL,
    external_code VARCHAR(100) NOT NULL,
    external_name VARCHAR(200),
    CONSTRAINT uq_region_external_code_mapping
        UNIQUE (region_code, source, external_code),
    CONSTRAINT chk_region_external_code_mapping_source CHECK (
        source IN (
            'SEOUL_ESTIMATED_SALES',
            'SMALL_BUSINESS_STORE',
            'KOSIS_BUSINESS_SURVIVAL_RATE',
            'KOSIS_BUSINESS_COUNT',
            'SEOUL_SDOT_FOOT_TRAFFIC'
        )
    )
);

CREATE INDEX idx_region_external_code_mappings_lookup
    ON region_external_code_mappings(region_code, source);
