CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'GENERAL',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_users_role CHECK (role IN ('OWNER', 'GENERAL', 'VISITOR', 'ADMIN')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE TABLE regions (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sido VARCHAR(50) NOT NULL,
    sigungu VARCHAR(50) NOT NULL,
    dong VARCHAR(80) NOT NULL,
    code VARCHAR(30),
    code_type VARCHAR(20) NOT NULL DEFAULT 'LEGAL_DONG',
    CONSTRAINT chk_regions_code_type CHECK (code_type IN ('LEGAL_DONG', 'ADMIN_DONG', 'SIGUNGU'))
);

CREATE UNIQUE INDEX uq_regions_code ON regions (code) WHERE code IS NOT NULL;
CREATE INDEX idx_regions_sido_sigungu_dong ON regions(sido, sigungu, dong);

CREATE TABLE commercial_areas (
    commercial_area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    type VARCHAR(30) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT chk_commercial_areas_type CHECK (
        type IN ('ALLEY', 'DEVELOPED', 'TRADITIONAL_MARKET', 'TOURISM_SPECIAL_ZONE')
    ),
    CONSTRAINT chk_commercial_areas_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE TABLE industries (
    industry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    parent_industry_id BIGINT REFERENCES industries(industry_id),
    level VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT chk_industries_level CHECK (level IN ('LARGE', 'MEDIUM', 'SMALL')),
    CONSTRAINT chk_industries_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE TABLE commercial_area_region_mappings (
    commercial_area_region_mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercial_area_id BIGINT NOT NULL REFERENCES commercial_areas(commercial_area_id),
    region_id BIGINT NOT NULL REFERENCES regions(region_id),
    is_primary BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uq_commercial_area_region UNIQUE (commercial_area_id, region_id)
);

CREATE TABLE buildings (
    building_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercial_area_id BIGINT NOT NULL REFERENCES commercial_areas(commercial_area_id),
    region_id BIGINT NOT NULL REFERENCES regions(region_id),
    address VARCHAR(255),
    name VARCHAR(150),
    total_floor INT DEFAULT 1,
    total_area DECIMAL(12,2),
    location GEOGRAPHY(POINT, 4326),
    CONSTRAINT chk_buildings_total_floor CHECK (total_floor IS NULL OR total_floor >= 0),
    CONSTRAINT chk_buildings_total_area CHECK (total_area IS NULL OR total_area >= 0)
);

CREATE INDEX idx_buildings_region_id ON buildings(region_id);
CREATE INDEX idx_buildings_commercial_area_id ON buildings(commercial_area_id);

CREATE TABLE stores (
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT NOT NULL REFERENCES buildings(building_id),
    industry_id BIGINT NOT NULL REFERENCES industries(industry_id),
    floor VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(80),
    area INT NOT NULL DEFAULT 0,
    deposit BIGINT NOT NULL DEFAULT 0,
    monthly_rent BIGINT NOT NULL DEFAULT 0,
    is_vacant BOOLEAN NOT NULL DEFAULT false,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_stores_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    CONSTRAINT chk_stores_amounts CHECK (area >= 0 AND deposit >= 0 AND monthly_rent >= 0)
);

CREATE UNIQUE INDEX uq_stores_code ON stores (code) WHERE code IS NOT NULL;
CREATE INDEX idx_stores_building_id ON stores(building_id);
CREATE INDEX idx_stores_industry_id ON stores(industry_id);

CREATE TABLE store_images (
    store_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(store_id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_store_images_display_order CHECK (display_order >= 0),
    CONSTRAINT uq_store_images_store_url UNIQUE (store_id, image_url)
);

CREATE INDEX idx_store_images_store_order ON store_images(store_id, display_order);

CREATE TABLE builder_stores (
    builder_store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    region_id BIGINT NOT NULL REFERENCES regions(region_id),
    commercial_area_id BIGINT NOT NULL REFERENCES commercial_areas(commercial_area_id),
    industry_id BIGINT NOT NULL REFERENCES industries(industry_id),
    base_building_id BIGINT REFERENCES buildings(building_id),
    name VARCHAR(150) NOT NULL,
    area INT NOT NULL DEFAULT 0,
    expected_monthly_sales BIGINT NOT NULL DEFAULT 0,
    expected_profit_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    investment_payback_months INT NOT NULL DEFAULT 0,
    property_score INT NOT NULL DEFAULT 0,
    monthly_rent BIGINT NOT NULL DEFAULT 0,
    deposit BIGINT NOT NULL DEFAULT 0,
    investment_amount BIGINT NOT NULL DEFAULT 0,
    description VARCHAR(1000),
    like_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    visibility_status VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_builder_stores_visibility CHECK (visibility_status IN ('PUBLIC', 'PRIVATE', 'DELETED')),
    CONSTRAINT chk_builder_stores_property_score CHECK (property_score BETWEEN 0 AND 100),
    CONSTRAINT chk_builder_stores_expected_profit_rate CHECK (expected_profit_rate BETWEEN -100 AND 1000),
    CONSTRAINT chk_builder_stores_non_negative CHECK (
        area >= 0 AND expected_monthly_sales >= 0 AND investment_payback_months >= 0
        AND monthly_rent >= 0 AND deposit >= 0 AND investment_amount >= 0
        AND like_count >= 0 AND comment_count >= 0
    )
);

CREATE INDEX idx_builder_stores_user_id ON builder_stores(user_id);
CREATE INDEX idx_builder_stores_region_id ON builder_stores(region_id);
CREATE INDEX idx_builder_stores_commercial_area_id ON builder_stores(commercial_area_id);
CREATE INDEX idx_builder_stores_industry_id ON builder_stores(industry_id);
CREATE INDEX idx_builder_stores_public_uploaded ON builder_stores(uploaded_at DESC) WHERE visibility_status = 'PUBLIC';
CREATE INDEX idx_builder_stores_public_likes ON builder_stores(like_count DESC) WHERE visibility_status = 'PUBLIC';
CREATE INDEX idx_builder_stores_public_sales ON builder_stores(expected_monthly_sales DESC) WHERE visibility_status = 'PUBLIC';
CREATE INDEX idx_builder_stores_public_profit ON builder_stores(expected_profit_rate DESC) WHERE visibility_status = 'PUBLIC';

CREATE TABLE builder_store_images (
    builder_store_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    builder_store_id BIGINT NOT NULL REFERENCES builder_stores(builder_store_id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_builder_store_images_display_order CHECK (display_order >= 0),
    CONSTRAINT uq_builder_store_images_store_url UNIQUE (builder_store_id, image_url)
);

CREATE INDEX idx_builder_store_images_store_order ON builder_store_images(builder_store_id, display_order);

CREATE TABLE builder_store_likes (
    builder_store_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    builder_store_id BIGINT NOT NULL REFERENCES builder_stores(builder_store_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_builder_store_likes UNIQUE (builder_store_id, user_id)
);

CREATE TABLE builder_store_bookmarks (
    builder_store_bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    builder_store_id BIGINT NOT NULL REFERENCES builder_stores(builder_store_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_builder_store_bookmarks UNIQUE (builder_store_id, user_id)
);

CREATE TABLE builder_store_comments (
    builder_store_comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    builder_store_id BIGINT NOT NULL REFERENCES builder_stores(builder_store_id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES builder_store_comments(builder_store_comment_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_refresh_tokens_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

CREATE TABLE store_operation_monthly_metrics (
    store_operation_monthly_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(store_id) ON DELETE RESTRICT,
    reference_month DATE NOT NULL,
    monthly_sales BIGINT NOT NULL DEFAULT 0,
    average_daily_sales BIGINT NOT NULL DEFAULT 0,
    customer_count BIGINT NOT NULL DEFAULT 0,
    average_order_amount BIGINT NOT NULL DEFAULT 0,
    revisit_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    table_turnover_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    delivery_sales_ratio DECIMAL(6,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_store_operation_month UNIQUE (store_id, reference_month),
    CONSTRAINT chk_store_operation_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT chk_store_operation_rates CHECK (
        revisit_rate BETWEEN 0 AND 100
        AND delivery_sales_ratio BETWEEN 0 AND 100
        AND table_turnover_rate >= 0
    ),
    CONSTRAINT chk_store_operation_non_negative CHECK (
        monthly_sales >= 0 AND average_daily_sales >= 0
        AND customer_count >= 0 AND average_order_amount >= 0
    )
);

CREATE TABLE store_financial_monthly_metrics (
    store_financial_monthly_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(store_id) ON DELETE RESTRICT,
    reference_month DATE NOT NULL,
    rent_amount BIGINT NOT NULL DEFAULT 0,
    labor_cost BIGINT NOT NULL DEFAULT 0,
    material_cost BIGINT NOT NULL DEFAULT 0,
    fixed_cost BIGINT NOT NULL DEFAULT 0,
    variable_cost BIGINT NOT NULL DEFAULT 0,
    cost_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    operating_profit BIGINT NOT NULL DEFAULT 0,
    operating_profit_rate DECIMAL(6,2),
    cash_flow BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_store_financial_month UNIQUE (store_id, reference_month),
    CONSTRAINT chk_store_financial_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT chk_store_financial_rates CHECK (
        cost_rate BETWEEN 0 AND 100
        AND (operating_profit_rate IS NULL OR operating_profit_rate BETWEEN -100 AND 1000)
    ),
    CONSTRAINT chk_store_financial_non_negative CHECK (
        rent_amount >= 0 AND labor_cost >= 0 AND material_cost >= 0
        AND fixed_cost >= 0 AND variable_cost >= 0
    )
);

CREATE TABLE industry_region_monthly_metrics (
    industry_region_monthly_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT NOT NULL REFERENCES regions(region_id),
    industry_id BIGINT NOT NULL REFERENCES industries(industry_id),
    reference_month DATE NOT NULL,
    average_sales BIGINT NOT NULL DEFAULT 0,
    sales_change_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    average_cost_rate DECIMAL(6,2),
    closure_rate DECIMAL(6,2),
    store_count BIGINT NOT NULL DEFAULT 0,
    sales_rank INT,
    source_name VARCHAR(100),
    collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_industry_region_month UNIQUE (region_id, industry_id, reference_month),
    CONSTRAINT chk_industry_region_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT chk_industry_region_rates CHECK (
        sales_change_rate BETWEEN -100 AND 1000
        AND (average_cost_rate IS NULL OR average_cost_rate BETWEEN 0 AND 100)
        AND (closure_rate IS NULL OR closure_rate BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_industry_region_non_negative CHECK (
        average_sales >= 0 AND store_count >= 0 AND (sales_rank IS NULL OR sales_rank > 0)
    )
);

CREATE TABLE commercial_area_monthly_metrics (
    commercial_area_monthly_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercial_area_id BIGINT NOT NULL REFERENCES commercial_areas(commercial_area_id),
    reference_month DATE NOT NULL,
    floating_population BIGINT NOT NULL DEFAULT 0,
    vacancy_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    average_rent BIGINT NOT NULL DEFAULT 0,
    opening_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    closure_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    sales_growth_rate DECIMAL(6,2) NOT NULL DEFAULT 0,
    competition_density DECIMAL(8,2) NOT NULL DEFAULT 0,
    activity_score INT NOT NULL DEFAULT 0,
    source_name VARCHAR(100),
    collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_commercial_area_month UNIQUE (commercial_area_id, reference_month),
    CONSTRAINT chk_commercial_area_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT chk_commercial_area_rates CHECK (
        vacancy_rate BETWEEN 0 AND 100 AND opening_rate BETWEEN 0 AND 100
        AND closure_rate BETWEEN 0 AND 100 AND sales_growth_rate BETWEEN -100 AND 1000
        AND competition_density >= 0 AND activity_score BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_commercial_area_non_negative CHECK (floating_population >= 0 AND average_rent >= 0)
);

CREATE TABLE floating_population_metrics (
    floating_population_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT REFERENCES regions(region_id),
    commercial_area_id BIGINT REFERENCES commercial_areas(commercial_area_id),
    reference_date DATE NOT NULL,
    time_slot_start TIME NOT NULL,
    age_group VARCHAR(20) NOT NULL,
    gender VARCHAR(10) NOT NULL DEFAULT 'ALL',
    population_count BIGINT NOT NULL DEFAULT 0,
    source_name VARCHAR(100),
    collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_floating_population_target CHECK (
        (region_id IS NOT NULL AND commercial_area_id IS NULL)
        OR (region_id IS NULL AND commercial_area_id IS NOT NULL)
    ),
    CONSTRAINT chk_floating_population_gender CHECK (gender IN ('MALE', 'FEMALE', 'ALL')),
    CONSTRAINT chk_floating_population_count CHECK (population_count >= 0)
);

CREATE UNIQUE INDEX uq_floating_population_region
ON floating_population_metrics (region_id, reference_date, time_slot_start, age_group, gender)
WHERE region_id IS NOT NULL;

CREATE UNIQUE INDEX uq_floating_population_commercial_area
ON floating_population_metrics (commercial_area_id, reference_date, time_slot_start, age_group, gender)
WHERE commercial_area_id IS NOT NULL;

CREATE INDEX idx_floating_population_region_date ON floating_population_metrics(region_id, reference_date);
CREATE INDEX idx_floating_population_commercial_area_date ON floating_population_metrics(commercial_area_id, reference_date);

CREATE TABLE rent_market_monthly_metrics (
    rent_market_monthly_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT REFERENCES regions(region_id),
    commercial_area_id BIGINT REFERENCES commercial_areas(commercial_area_id),
    reference_month DATE NOT NULL,
    average_rent_per_area BIGINT,
    average_deposit BIGINT,
    vacancy_rate DECIMAL(6,2),
    rent_change_rate DECIMAL(6,2),
    source_name VARCHAR(100),
    collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_rent_market_target CHECK (
        (region_id IS NOT NULL AND commercial_area_id IS NULL)
        OR (region_id IS NULL AND commercial_area_id IS NOT NULL)
    ),
    CONSTRAINT chk_rent_market_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT chk_rent_market_rates CHECK (
        (vacancy_rate IS NULL OR vacancy_rate BETWEEN 0 AND 100)
        AND (rent_change_rate IS NULL OR rent_change_rate BETWEEN -100 AND 1000)
    )
);

CREATE UNIQUE INDEX uq_rent_market_region_month
ON rent_market_monthly_metrics (region_id, reference_month)
WHERE region_id IS NOT NULL;

CREATE UNIQUE INDEX uq_rent_market_commercial_area_month
ON rent_market_monthly_metrics (commercial_area_id, reference_month)
WHERE commercial_area_id IS NOT NULL;

CREATE INDEX idx_rent_market_region_month ON rent_market_monthly_metrics(region_id, reference_month);
CREATE INDEX idx_rent_market_commercial_area_month ON rent_market_monthly_metrics(commercial_area_id, reference_month);

CREATE TABLE real_estate_transactions (
    real_estate_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT NOT NULL REFERENCES regions(region_id),
    building_id BIGINT REFERENCES buildings(building_id),
    transaction_date DATE NOT NULL,
    transaction_price BIGINT NOT NULL,
    address VARCHAR(255) NOT NULL,
    area DECIMAL(12,2),
    price_per_area BIGINT,
    cap_rate DECIMAL(6,2),
    source_name VARCHAR(100),
    collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_real_estate_transaction_values CHECK (
        transaction_price >= 0
        AND (area IS NULL OR area >= 0)
        AND (price_per_area IS NULL OR price_per_area >= 0)
        AND (cap_rate IS NULL OR cap_rate BETWEEN 0 AND 100)
    )
);

CREATE INDEX idx_real_estate_transactions_region_date ON real_estate_transactions(region_id, transaction_date);
CREATE INDEX idx_real_estate_transactions_building_id ON real_estate_transactions(building_id);

CREATE TABLE builder_store_ranking_snapshots (
    builder_store_ranking_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    builder_store_id BIGINT NOT NULL REFERENCES builder_stores(builder_store_id) ON DELETE CASCADE,
    ranking_type VARCHAR(30) NOT NULL,
    ranking INT NOT NULL,
    reference_month DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_builder_store_ranking_type CHECK (ranking_type IN ('SALES', 'PROFIT', 'LIKES')),
    CONSTRAINT chk_builder_store_ranking_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT uq_builder_store_ranking UNIQUE (builder_store_id, ranking_type, reference_month)
);

CREATE TABLE score_snapshots (
    score_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL,
    store_id BIGINT REFERENCES stores(store_id) ON DELETE RESTRICT,
    builder_store_id BIGINT REFERENCES builder_stores(builder_store_id) ON DELETE CASCADE,
    commercial_area_id BIGINT REFERENCES commercial_areas(commercial_area_id) ON DELETE RESTRICT,
    region_id BIGINT REFERENCES regions(region_id) ON DELETE RESTRICT,
    score_type VARCHAR(20) NOT NULL,
    reference_month DATE NOT NULL,
    total_score DECIMAL(5,2) NOT NULL,
    grade VARCHAR(5) NOT NULL,
    pd DECIMAL(6,2),
    survival_probability DECIMAL(6,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_score_target_type CHECK (target_type IN ('STORE', 'BUILDER_STORE', 'COMMERCIAL_AREA', 'REGION')),
    CONSTRAINT chk_score_type CHECK (score_type IN ('RISK', 'PROPERTY')),
    CONSTRAINT chk_score_grade CHECK (grade IN ('A', 'B', 'C', 'D', 'E')),
    CONSTRAINT chk_score_reference_month CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT chk_score_values CHECK (
        total_score BETWEEN 0 AND 100
        AND (pd IS NULL OR pd BETWEEN 0 AND 100)
        AND (survival_probability IS NULL OR survival_probability BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_score_target_fk CHECK (
        (target_type = 'STORE' AND store_id IS NOT NULL AND builder_store_id IS NULL AND commercial_area_id IS NULL AND region_id IS NULL)
        OR (target_type = 'BUILDER_STORE' AND store_id IS NULL AND builder_store_id IS NOT NULL AND commercial_area_id IS NULL AND region_id IS NULL)
        OR (target_type = 'COMMERCIAL_AREA' AND store_id IS NULL AND builder_store_id IS NULL AND commercial_area_id IS NOT NULL AND region_id IS NULL)
        OR (target_type = 'REGION' AND store_id IS NULL AND builder_store_id IS NULL AND commercial_area_id IS NULL AND region_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_score_store_month
ON score_snapshots (store_id, score_type, reference_month)
WHERE target_type = 'STORE';

CREATE UNIQUE INDEX uq_score_builder_store_month
ON score_snapshots (builder_store_id, score_type, reference_month)
WHERE target_type = 'BUILDER_STORE';

CREATE UNIQUE INDEX uq_score_commercial_area_month
ON score_snapshots (commercial_area_id, score_type, reference_month)
WHERE target_type = 'COMMERCIAL_AREA';

CREATE UNIQUE INDEX uq_score_region_month
ON score_snapshots (region_id, score_type, reference_month)
WHERE target_type = 'REGION';

CREATE TABLE score_component_snapshots (
    score_component_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_snapshot_id BIGINT NOT NULL REFERENCES score_snapshots(score_snapshot_id) ON DELETE CASCADE,
    component_type VARCHAR(30) NOT NULL,
    raw_value DECIMAL(18,4),
    normalized_score DECIMAL(6,2),
    weight DECIMAL(6,4),
    contribution DECIMAL(8,4),
    CONSTRAINT chk_score_component_type CHECK (
        component_type IN ('OPERATING', 'FINANCIAL', 'MARKET', 'REGIONAL', 'SUCCESSION', 'INCOME', 'RISK', 'LIQUIDITY')
    )
);

CREATE INDEX idx_score_components_score_snapshot_id ON score_component_snapshots(score_snapshot_id);
