-- 실행 이력과 임시 적재 데이터는 장애 복구를 위해 LOGGED로 유지한다.
CREATE TABLE public_data_batch_leases (
    data_type VARCHAR(80) PRIMARY KEY,
    owner_token UUID NOT NULL,
    lease_until TIMESTAMPTZ NOT NULL
);

CREATE TABLE public_data_batch_pages (
    page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_execution_id BIGINT NOT NULL REFERENCES batch_job_execution(job_execution_id),
    data_type VARCHAR(80) NOT NULL,
    storage_target TEXT,
    payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'array'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_public_data_batch_pages_execution
    ON public_data_batch_pages(job_execution_id, page_id);
CREATE INDEX idx_public_data_batch_pages_type ON public_data_batch_pages(data_type);

CREATE TABLE public_data_batch_publications (
    data_type VARCHAR(80) PRIMARY KEY,
    job_execution_id BIGINT NOT NULL REFERENCES batch_job_execution(job_execution_id),
    row_count BIGINT NOT NULL CHECK (row_count > 0),
    published_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
