CREATE TABLE commercial_estimated_sales (
    commercial_estimated_sales_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stdr_yyqu_cd VARCHAR(5) NOT NULL,
    trdar_se_cd VARCHAR(20),
    trdar_se_cd_nm VARCHAR(100),
    trdar_cd VARCHAR(30) NOT NULL,
    trdar_cd_nm VARCHAR(150),
    svc_induty_cd VARCHAR(30) NOT NULL,
    svc_induty_cd_nm VARCHAR(100),

    thsmon_selng_amt BIGINT NOT NULL DEFAULT 0,
    thsmon_selng_co BIGINT NOT NULL DEFAULT 0,

    mdwk_selng_amt BIGINT NOT NULL DEFAULT 0,
    wkend_selng_amt BIGINT NOT NULL DEFAULT 0,
    mon_selng_amt BIGINT NOT NULL DEFAULT 0,
    tues_selng_amt BIGINT NOT NULL DEFAULT 0,
    wed_selng_amt BIGINT NOT NULL DEFAULT 0,
    thur_selng_amt BIGINT NOT NULL DEFAULT 0,
    fri_selng_amt BIGINT NOT NULL DEFAULT 0,
    sat_selng_amt BIGINT NOT NULL DEFAULT 0,
    sun_selng_amt BIGINT NOT NULL DEFAULT 0,

    tmzon_00_06_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_06_11_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_11_14_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_14_17_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_17_21_selng_amt BIGINT NOT NULL DEFAULT 0,
    tmzon_21_24_selng_amt BIGINT NOT NULL DEFAULT 0,

    ml_selng_amt BIGINT NOT NULL DEFAULT 0,
    fml_selng_amt BIGINT NOT NULL DEFAULT 0,

    agrde_10_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_20_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_30_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_40_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_50_selng_amt BIGINT NOT NULL DEFAULT 0,
    agrde_60_above_selng_amt BIGINT NOT NULL DEFAULT 0,

    mdwk_selng_co BIGINT NOT NULL DEFAULT 0,
    wkend_selng_co BIGINT NOT NULL DEFAULT 0,
    mon_selng_co BIGINT NOT NULL DEFAULT 0,
    tues_selng_co BIGINT NOT NULL DEFAULT 0,
    wed_selng_co BIGINT NOT NULL DEFAULT 0,
    thur_selng_co BIGINT NOT NULL DEFAULT 0,
    fri_selng_co BIGINT NOT NULL DEFAULT 0,
    sat_selng_co BIGINT NOT NULL DEFAULT 0,
    sun_selng_co BIGINT NOT NULL DEFAULT 0,

    tmzon_00_06_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_06_11_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_11_14_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_14_17_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_17_21_selng_co BIGINT NOT NULL DEFAULT 0,
    tmzon_21_24_selng_co BIGINT NOT NULL DEFAULT 0,

    ml_selng_co BIGINT NOT NULL DEFAULT 0,
    fml_selng_co BIGINT NOT NULL DEFAULT 0,

    agrde_10_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_20_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_30_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_40_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_50_selng_co BIGINT NOT NULL DEFAULT 0,
    agrde_60_above_selng_co BIGINT NOT NULL DEFAULT 0,

    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_commercial_estimated_sales_quarter_area_industry
        UNIQUE (stdr_yyqu_cd, trdar_cd, svc_induty_cd),

    CONSTRAINT chk_commercial_estimated_sales_amounts CHECK (
        thsmon_selng_amt >= 0
        AND thsmon_selng_co >= 0
        AND mdwk_selng_amt >= 0
        AND wkend_selng_amt >= 0
        AND mon_selng_amt >= 0
        AND tues_selng_amt >= 0
        AND wed_selng_amt >= 0
        AND thur_selng_amt >= 0
        AND fri_selng_amt >= 0
        AND sat_selng_amt >= 0
        AND sun_selng_amt >= 0
        AND mdwk_selng_co >= 0
        AND wkend_selng_co >= 0
        AND mon_selng_co >= 0
        AND tues_selng_co >= 0
        AND wed_selng_co >= 0
        AND thur_selng_co >= 0
        AND fri_selng_co >= 0
        AND sat_selng_co >= 0
        AND sun_selng_co >= 0
    )
);

CREATE INDEX idx_commercial_estimated_sales_stdr_yyqu_cd
    ON commercial_estimated_sales(stdr_yyqu_cd);

CREATE INDEX idx_commercial_estimated_sales_trdar_cd
    ON commercial_estimated_sales(trdar_cd);

CREATE INDEX idx_commercial_estimated_sales_svc_induty_cd
    ON commercial_estimated_sales(svc_induty_cd);


CREATE TABLE commercial_data_collect_histories (
    commercial_data_collect_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR(100) NOT NULL,
    target_key VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_count BIGINT NOT NULL DEFAULT 0,
    fetched_count BIGINT NOT NULL DEFAULT 0,
    last_start_index BIGINT NOT NULL DEFAULT 0,
    error_message VARCHAR(2000),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,

    CONSTRAINT chk_commercial_data_collect_histories_status
        CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE UNIQUE INDEX uq_commercial_data_collect_histories_completed
    ON commercial_data_collect_histories(data_type, target_key)
    WHERE status = 'COMPLETED';

CREATE INDEX idx_commercial_data_collect_histories_data_type_target_key
    ON commercial_data_collect_histories(data_type, target_key);
