-- 공공데이터 원문을 보존하고 내부 stores 도메인과는 별도로 관리한다.
CREATE TABLE small_business_stores (
    small_business_store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id VARCHAR(30) NOT NULL,
    commercial_area_code VARCHAR(30) NOT NULL,
    store_name VARCHAR(200) NOT NULL,
    branch_name VARCHAR(200),
    large_industry_code VARCHAR(10),
    large_industry_name VARCHAR(100),
    medium_industry_code VARCHAR(10),
    medium_industry_name VARCHAR(100),
    small_industry_code VARCHAR(10),
    small_industry_name VARCHAR(100),
    standard_industry_code VARCHAR(20),
    standard_industry_name VARCHAR(150),
    sido_code VARCHAR(10),
    sido_name VARCHAR(50),
    sigungu_code VARCHAR(10),
    sigungu_name VARCHAR(50),
    administrative_dong_code VARCHAR(20),
    administrative_dong_name VARCHAR(50),
    legal_dong_code VARCHAR(20),
    legal_dong_name VARCHAR(50),
    lot_number_address VARCHAR(500),
    road_name_address VARCHAR(500),
    building_management_number VARCHAR(30),
    building_name VARCHAR(200),
    floor_number VARCHAR(30),
    room_number VARCHAR(30),
    longitude DECIMAL(12, 8),
    latitude DECIMAL(12, 8),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_small_business_stores_store_id UNIQUE (store_id)
);

CREATE INDEX idx_small_business_stores_commercial_area_code
    ON small_business_stores(commercial_area_code);

CREATE INDEX idx_small_business_stores_industry
    ON small_business_stores(large_industry_code, medium_industry_code, small_industry_code);

CREATE INDEX idx_small_business_stores_administrative_dong
    ON small_business_stores(administrative_dong_code);

CREATE INDEX idx_small_business_stores_legal_dong
    ON small_business_stores(legal_dong_code);
