CREATE TABLE reb_small_retail_rent_areas (
    reb_small_retail_rent_area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_area_key VARCHAR(64) NOT NULL,
    source_row_number INTEGER NOT NULL,
    area_name VARCHAR(100) NOT NULL,
    area_path VARCHAR(500) NOT NULL,
    area_level SMALLINT NOT NULL,
    region_id BIGINT REFERENCES regions(region_id),
    commercial_area_id BIGINT REFERENCES commercial_areas(commercial_area_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT uq_reb_small_retail_rent_areas_source_key UNIQUE (source_area_key),
    CONSTRAINT ck_reb_small_retail_rent_areas_single_mapping CHECK (
        region_id IS NULL OR commercial_area_id IS NULL
    )
);

CREATE TABLE reb_small_retail_rent_metrics (
    reb_small_retail_rent_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reb_small_retail_rent_area_id BIGINT NOT NULL
        REFERENCES reb_small_retail_rent_areas(reb_small_retail_rent_area_id),
    reference_year SMALLINT NOT NULL,
    reference_quarter SMALLINT NOT NULL,
    rent_per_square_meter_thousand_krw DECIMAL(12, 3) NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    source_file_hash VARCHAR(64) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT ck_reb_small_retail_rent_metrics_quarter CHECK (reference_quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_reb_small_retail_rent_metrics_rent CHECK (
        rent_per_square_meter_thousand_krw >= 0
    ),
    CONSTRAINT uq_reb_small_retail_rent_metrics_area_period UNIQUE (
        reb_small_retail_rent_area_id, reference_year, reference_quarter
    )
);

CREATE INDEX idx_reb_small_retail_rent_areas_region
    ON reb_small_retail_rent_areas(region_id);

CREATE INDEX idx_reb_small_retail_rent_areas_commercial_area
    ON reb_small_retail_rent_areas(commercial_area_id);

CREATE INDEX idx_reb_small_retail_rent_metrics_period
    ON reb_small_retail_rent_metrics(reference_year, reference_quarter);
